//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Panda.Phone.ServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecycleActivitys", Namespace="http://schemas.datacontract.org/2004/07/Panda.Phone.DataModel")]
    public partial class RecycleActivitys : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime EndTimeField;
        
        private System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.Adrress> LocationListField;
        
        private string NameField;
        
        private System.DateTime StartTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.Adrress> LocationList {
            get {
                return this.LocationListField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationListField, value) != true)) {
                    this.LocationListField = value;
                    this.RaisePropertyChanged("LocationList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adrress", Namespace="http://schemas.datacontract.org/2004/07/Panda.Phone.DataModel")]
    public partial class Adrress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecycleFriends", Namespace="http://schemas.datacontract.org/2004/07/Panda.Phone.DataModel")]
    public partial class RecycleFriends : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleActivitys> ActivityListField;
        
        private string ImageField;
        
        private string LatestActivityField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleActivitys> ActivityList {
            get {
                return this.ActivityListField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityListField, value) != true)) {
                    this.ActivityListField = value;
                    this.RaisePropertyChanged("ActivityList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LatestActivity {
            get {
                return this.LatestActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.LatestActivityField, value) != true)) {
                    this.LatestActivityField = value;
                    this.RaisePropertyChanged("LatestActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IPhoneService")]
    public interface IPhoneService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPushNotificationService/Register", ReplyAction="http://tempuri.org/IPushNotificationService/RegisterResponse")]
        System.IAsyncResult BeginRegister(string uri, System.AsyncCallback callback, object asyncState);
        
        void EndRegister(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneService/getRecycleActivityList", ReplyAction="http://tempuri.org/IPhoneService/getRecycleActivityListResponse")]
        System.IAsyncResult BegingetRecycleActivityList(string uri, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleActivitys> EndgetRecycleActivityList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneService/getRecycleFriendList", ReplyAction="http://tempuri.org/IPhoneService/getRecycleFriendListResponse")]
        System.IAsyncResult BegingetRecycleFriendList(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleFriends> EndgetRecycleFriendList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPhoneService/getAddressByName", ReplyAction="http://tempuri.org/IPhoneService/getAddressByNameResponse")]
        System.IAsyncResult BegingetAddressByName(string name, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.Adrress> EndgetAddressByName(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPhoneServiceChannel : Panda.Phone.ServiceReference.IPhoneService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getRecycleActivityListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getRecycleActivityListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleActivitys> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleActivitys>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getRecycleFriendListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getRecycleFriendListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleFriends> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleFriends>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAddressByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAddressByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.Adrress> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.Adrress>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PhoneServiceClient : System.ServiceModel.ClientBase<Panda.Phone.ServiceReference.IPhoneService>, Panda.Phone.ServiceReference.IPhoneService {
        
        private BeginOperationDelegate onBeginRegisterDelegate;
        
        private EndOperationDelegate onEndRegisterDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterCompletedDelegate;
        
        private BeginOperationDelegate onBegingetRecycleActivityListDelegate;
        
        private EndOperationDelegate onEndgetRecycleActivityListDelegate;
        
        private System.Threading.SendOrPostCallback ongetRecycleActivityListCompletedDelegate;
        
        private BeginOperationDelegate onBegingetRecycleFriendListDelegate;
        
        private EndOperationDelegate onEndgetRecycleFriendListDelegate;
        
        private System.Threading.SendOrPostCallback ongetRecycleFriendListCompletedDelegate;
        
        private BeginOperationDelegate onBegingetAddressByNameDelegate;
        
        private EndOperationDelegate onEndgetAddressByNameDelegate;
        
        private System.Threading.SendOrPostCallback ongetAddressByNameCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PhoneServiceClient() {
        }
        
        public PhoneServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PhoneServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PhoneServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RegisterCompleted;
        
        public event System.EventHandler<getRecycleActivityListCompletedEventArgs> getRecycleActivityListCompleted;
        
        public event System.EventHandler<getRecycleFriendListCompletedEventArgs> getRecycleFriendListCompleted;
        
        public event System.EventHandler<getAddressByNameCompletedEventArgs> getAddressByNameCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Panda.Phone.ServiceReference.IPhoneService.BeginRegister(string uri, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegister(uri, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Panda.Phone.ServiceReference.IPhoneService.EndRegister(System.IAsyncResult result) {
            base.Channel.EndRegister(result);
        }
        
        private System.IAsyncResult OnBeginRegister(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uri = ((string)(inValues[0]));
            return ((Panda.Phone.ServiceReference.IPhoneService)(this)).BeginRegister(uri, callback, asyncState);
        }
        
        private object[] OnEndRegister(System.IAsyncResult result) {
            ((Panda.Phone.ServiceReference.IPhoneService)(this)).EndRegister(result);
            return null;
        }
        
        private void OnRegisterCompleted(object state) {
            if ((this.RegisterCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterAsync(string uri) {
            this.RegisterAsync(uri, null);
        }
        
        public void RegisterAsync(string uri, object userState) {
            if ((this.onBeginRegisterDelegate == null)) {
                this.onBeginRegisterDelegate = new BeginOperationDelegate(this.OnBeginRegister);
            }
            if ((this.onEndRegisterDelegate == null)) {
                this.onEndRegisterDelegate = new EndOperationDelegate(this.OnEndRegister);
            }
            if ((this.onRegisterCompletedDelegate == null)) {
                this.onRegisterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterDelegate, new object[] {
                        uri}, this.onEndRegisterDelegate, this.onRegisterCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Panda.Phone.ServiceReference.IPhoneService.BegingetRecycleActivityList(string uri, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetRecycleActivityList(uri, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleActivitys> Panda.Phone.ServiceReference.IPhoneService.EndgetRecycleActivityList(System.IAsyncResult result) {
            return base.Channel.EndgetRecycleActivityList(result);
        }
        
        private System.IAsyncResult OnBegingetRecycleActivityList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uri = ((string)(inValues[0]));
            return ((Panda.Phone.ServiceReference.IPhoneService)(this)).BegingetRecycleActivityList(uri, callback, asyncState);
        }
        
        private object[] OnEndgetRecycleActivityList(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleActivitys> retVal = ((Panda.Phone.ServiceReference.IPhoneService)(this)).EndgetRecycleActivityList(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetRecycleActivityListCompleted(object state) {
            if ((this.getRecycleActivityListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getRecycleActivityListCompleted(this, new getRecycleActivityListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getRecycleActivityListAsync(string uri) {
            this.getRecycleActivityListAsync(uri, null);
        }
        
        public void getRecycleActivityListAsync(string uri, object userState) {
            if ((this.onBegingetRecycleActivityListDelegate == null)) {
                this.onBegingetRecycleActivityListDelegate = new BeginOperationDelegate(this.OnBegingetRecycleActivityList);
            }
            if ((this.onEndgetRecycleActivityListDelegate == null)) {
                this.onEndgetRecycleActivityListDelegate = new EndOperationDelegate(this.OnEndgetRecycleActivityList);
            }
            if ((this.ongetRecycleActivityListCompletedDelegate == null)) {
                this.ongetRecycleActivityListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetRecycleActivityListCompleted);
            }
            base.InvokeAsync(this.onBegingetRecycleActivityListDelegate, new object[] {
                        uri}, this.onEndgetRecycleActivityListDelegate, this.ongetRecycleActivityListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Panda.Phone.ServiceReference.IPhoneService.BegingetRecycleFriendList(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetRecycleFriendList(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleFriends> Panda.Phone.ServiceReference.IPhoneService.EndgetRecycleFriendList(System.IAsyncResult result) {
            return base.Channel.EndgetRecycleFriendList(result);
        }
        
        private System.IAsyncResult OnBegingetRecycleFriendList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Panda.Phone.ServiceReference.IPhoneService)(this)).BegingetRecycleFriendList(callback, asyncState);
        }
        
        private object[] OnEndgetRecycleFriendList(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleFriends> retVal = ((Panda.Phone.ServiceReference.IPhoneService)(this)).EndgetRecycleFriendList(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetRecycleFriendListCompleted(object state) {
            if ((this.getRecycleFriendListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getRecycleFriendListCompleted(this, new getRecycleFriendListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getRecycleFriendListAsync() {
            this.getRecycleFriendListAsync(null);
        }
        
        public void getRecycleFriendListAsync(object userState) {
            if ((this.onBegingetRecycleFriendListDelegate == null)) {
                this.onBegingetRecycleFriendListDelegate = new BeginOperationDelegate(this.OnBegingetRecycleFriendList);
            }
            if ((this.onEndgetRecycleFriendListDelegate == null)) {
                this.onEndgetRecycleFriendListDelegate = new EndOperationDelegate(this.OnEndgetRecycleFriendList);
            }
            if ((this.ongetRecycleFriendListCompletedDelegate == null)) {
                this.ongetRecycleFriendListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetRecycleFriendListCompleted);
            }
            base.InvokeAsync(this.onBegingetRecycleFriendListDelegate, null, this.onEndgetRecycleFriendListDelegate, this.ongetRecycleFriendListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Panda.Phone.ServiceReference.IPhoneService.BegingetAddressByName(string name, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAddressByName(name, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.Adrress> Panda.Phone.ServiceReference.IPhoneService.EndgetAddressByName(System.IAsyncResult result) {
            return base.Channel.EndgetAddressByName(result);
        }
        
        private System.IAsyncResult OnBegingetAddressByName(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            return ((Panda.Phone.ServiceReference.IPhoneService)(this)).BegingetAddressByName(name, callback, asyncState);
        }
        
        private object[] OnEndgetAddressByName(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.Adrress> retVal = ((Panda.Phone.ServiceReference.IPhoneService)(this)).EndgetAddressByName(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAddressByNameCompleted(object state) {
            if ((this.getAddressByNameCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAddressByNameCompleted(this, new getAddressByNameCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAddressByNameAsync(string name) {
            this.getAddressByNameAsync(name, null);
        }
        
        public void getAddressByNameAsync(string name, object userState) {
            if ((this.onBegingetAddressByNameDelegate == null)) {
                this.onBegingetAddressByNameDelegate = new BeginOperationDelegate(this.OnBegingetAddressByName);
            }
            if ((this.onEndgetAddressByNameDelegate == null)) {
                this.onEndgetAddressByNameDelegate = new EndOperationDelegate(this.OnEndgetAddressByName);
            }
            if ((this.ongetAddressByNameCompletedDelegate == null)) {
                this.ongetAddressByNameCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAddressByNameCompleted);
            }
            base.InvokeAsync(this.onBegingetAddressByNameDelegate, new object[] {
                        name}, this.onEndgetAddressByNameDelegate, this.ongetAddressByNameCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Panda.Phone.ServiceReference.IPhoneService CreateChannel() {
            return new PhoneServiceClientChannel(this);
        }
        
        private class PhoneServiceClientChannel : ChannelBase<Panda.Phone.ServiceReference.IPhoneService>, Panda.Phone.ServiceReference.IPhoneService {
            
            public PhoneServiceClientChannel(System.ServiceModel.ClientBase<Panda.Phone.ServiceReference.IPhoneService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRegister(string uri, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = uri;
                System.IAsyncResult _result = base.BeginInvoke("Register", _args, callback, asyncState);
                return _result;
            }
            
            public void EndRegister(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Register", _args, result);
            }
            
            public System.IAsyncResult BegingetRecycleActivityList(string uri, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = uri;
                System.IAsyncResult _result = base.BeginInvoke("getRecycleActivityList", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleActivitys> EndgetRecycleActivityList(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleActivitys> _result = ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleActivitys>)(base.EndInvoke("getRecycleActivityList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetRecycleFriendList(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getRecycleFriendList", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleFriends> EndgetRecycleFriendList(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleFriends> _result = ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.RecycleFriends>)(base.EndInvoke("getRecycleFriendList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetAddressByName(string name, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = name;
                System.IAsyncResult _result = base.BeginInvoke("getAddressByName", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.Adrress> EndgetAddressByName(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.Adrress> _result = ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.ServiceReference.Adrress>)(base.EndInvoke("getAddressByName", _args, result)));
                return _result;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IPushNotificationService")]
    public interface IPushNotificationService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IPushNotificationService/Register", ReplyAction="http://tempuri.org/IPushNotificationService/RegisterResponse")]
        System.IAsyncResult BeginRegister(string uri, System.AsyncCallback callback, object asyncState);
        
        void EndRegister(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPushNotificationServiceChannel : Panda.Phone.ServiceReference.IPushNotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PushNotificationServiceClient : System.ServiceModel.ClientBase<Panda.Phone.ServiceReference.IPushNotificationService>, Panda.Phone.ServiceReference.IPushNotificationService {
        
        private BeginOperationDelegate onBeginRegisterDelegate;
        
        private EndOperationDelegate onEndRegisterDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public PushNotificationServiceClient() {
        }
        
        public PushNotificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PushNotificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushNotificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PushNotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RegisterCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Panda.Phone.ServiceReference.IPushNotificationService.BeginRegister(string uri, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegister(uri, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Panda.Phone.ServiceReference.IPushNotificationService.EndRegister(System.IAsyncResult result) {
            base.Channel.EndRegister(result);
        }
        
        private System.IAsyncResult OnBeginRegister(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string uri = ((string)(inValues[0]));
            return ((Panda.Phone.ServiceReference.IPushNotificationService)(this)).BeginRegister(uri, callback, asyncState);
        }
        
        private object[] OnEndRegister(System.IAsyncResult result) {
            ((Panda.Phone.ServiceReference.IPushNotificationService)(this)).EndRegister(result);
            return null;
        }
        
        private void OnRegisterCompleted(object state) {
            if ((this.RegisterCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterAsync(string uri) {
            this.RegisterAsync(uri, null);
        }
        
        public void RegisterAsync(string uri, object userState) {
            if ((this.onBeginRegisterDelegate == null)) {
                this.onBeginRegisterDelegate = new BeginOperationDelegate(this.OnBeginRegister);
            }
            if ((this.onEndRegisterDelegate == null)) {
                this.onEndRegisterDelegate = new EndOperationDelegate(this.OnEndRegister);
            }
            if ((this.onRegisterCompletedDelegate == null)) {
                this.onRegisterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterDelegate, new object[] {
                        uri}, this.onEndRegisterDelegate, this.onRegisterCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Panda.Phone.ServiceReference.IPushNotificationService CreateChannel() {
            return new PushNotificationServiceClientChannel(this);
        }
        
        private class PushNotificationServiceClientChannel : ChannelBase<Panda.Phone.ServiceReference.IPushNotificationService>, Panda.Phone.ServiceReference.IPushNotificationService {
            
            public PushNotificationServiceClientChannel(System.ServiceModel.ClientBase<Panda.Phone.ServiceReference.IPushNotificationService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRegister(string uri, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = uri;
                System.IAsyncResult _result = base.BeginInvoke("Register", _args, callback, asyncState);
                return _result;
            }
            
            public void EndRegister(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Register", _args, result);
            }
        }
    }
}
