//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Becle.Server.Database
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class BecleEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“BecleEntities”部分中的连接字符串初始化新 BecleEntities 对象。
        /// </summary>
        public BecleEntities() : base("name=BecleEntities", "BecleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 BecleEntities 对象。
        /// </summary>
        public BecleEntities(string connectionString) : base(connectionString, "BecleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 BecleEntities 对象。
        /// </summary>
        public BecleEntities(EntityConnection connection) : base(connection, "BecleEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<AchievementTrendTable> AchievementTrendTables
        {
            get
            {
                if ((_AchievementTrendTables == null))
                {
                    _AchievementTrendTables = base.CreateObjectSet<AchievementTrendTable>("AchievementTrendTables");
                }
                return _AchievementTrendTables;
            }
        }
        private ObjectSet<AchievementTrendTable> _AchievementTrendTables;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<AcquirerTable> AcquirerTables
        {
            get
            {
                if ((_AcquirerTables == null))
                {
                    _AcquirerTables = base.CreateObjectSet<AcquirerTable>("AcquirerTables");
                }
                return _AcquirerTables;
            }
        }
        private ObjectSet<AcquirerTable> _AcquirerTables;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CategoryTable> CategoryTables
        {
            get
            {
                if ((_CategoryTables == null))
                {
                    _CategoryTables = base.CreateObjectSet<CategoryTable>("CategoryTables");
                }
                return _CategoryTables;
            }
        }
        private ObjectSet<CategoryTable> _CategoryTables;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<CityTable> CityTables
        {
            get
            {
                if ((_CityTables == null))
                {
                    _CityTables = base.CreateObjectSet<CityTable>("CityTables");
                }
                return _CityTables;
            }
        }
        private ObjectSet<CityTable> _CityTables;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<FriendTable> FriendTables
        {
            get
            {
                if ((_FriendTables == null))
                {
                    _FriendTables = base.CreateObjectSet<FriendTable>("FriendTables");
                }
                return _FriendTables;
            }
        }
        private ObjectSet<FriendTable> _FriendTables;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<ItemTable> ItemTables
        {
            get
            {
                if ((_ItemTables == null))
                {
                    _ItemTables = base.CreateObjectSet<ItemTable>("ItemTables");
                }
                return _ItemTables;
            }
        }
        private ObjectSet<ItemTable> _ItemTables;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MerChantTable> MerChantTables
        {
            get
            {
                if ((_MerChantTables == null))
                {
                    _MerChantTables = base.CreateObjectSet<MerChantTable>("MerChantTables");
                }
                return _MerChantTables;
            }
        }
        private ObjectSet<MerChantTable> _MerChantTables;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MessageTable> MessageTables
        {
            get
            {
                if ((_MessageTables == null))
                {
                    _MessageTables = base.CreateObjectSet<MessageTable>("MessageTables");
                }
                return _MessageTables;
            }
        }
        private ObjectSet<MessageTable> _MessageTables;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<MessageToUserTable> MessageToUserTables
        {
            get
            {
                if ((_MessageToUserTables == null))
                {
                    _MessageToUserTables = base.CreateObjectSet<MessageToUserTable>("MessageToUserTables");
                }
                return _MessageToUserTables;
            }
        }
        private ObjectSet<MessageToUserTable> _MessageToUserTables;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<PhotoTrendTable> PhotoTrendTables
        {
            get
            {
                if ((_PhotoTrendTables == null))
                {
                    _PhotoTrendTables = base.CreateObjectSet<PhotoTrendTable>("PhotoTrendTables");
                }
                return _PhotoTrendTables;
            }
        }
        private ObjectSet<PhotoTrendTable> _PhotoTrendTables;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<PostAffectTable> PostAffectTables
        {
            get
            {
                if ((_PostAffectTables == null))
                {
                    _PostAffectTables = base.CreateObjectSet<PostAffectTable>("PostAffectTables");
                }
                return _PostAffectTables;
            }
        }
        private ObjectSet<PostAffectTable> _PostAffectTables;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<RewardTable> RewardTables
        {
            get
            {
                if ((_RewardTables == null))
                {
                    _RewardTables = base.CreateObjectSet<RewardTable>("RewardTables");
                }
                return _RewardTables;
            }
        }
        private ObjectSet<RewardTable> _RewardTables;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<UserTable> UserTables
        {
            get
            {
                if ((_UserTables == null))
                {
                    _UserTables = base.CreateObjectSet<UserTable>("UserTables");
                }
                return _UserTables;
            }
        }
        private ObjectSet<UserTable> _UserTables;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 AchievementTrendTables EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToAchievementTrendTables(AchievementTrendTable achievementTrendTable)
        {
            base.AddObject("AchievementTrendTables", achievementTrendTable);
        }
    
        /// <summary>
        /// 用于向 AcquirerTables EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToAcquirerTables(AcquirerTable acquirerTable)
        {
            base.AddObject("AcquirerTables", acquirerTable);
        }
    
        /// <summary>
        /// 用于向 CategoryTables EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToCategoryTables(CategoryTable categoryTable)
        {
            base.AddObject("CategoryTables", categoryTable);
        }
    
        /// <summary>
        /// 用于向 CityTables EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToCityTables(CityTable cityTable)
        {
            base.AddObject("CityTables", cityTable);
        }
    
        /// <summary>
        /// 用于向 FriendTables EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToFriendTables(FriendTable friendTable)
        {
            base.AddObject("FriendTables", friendTable);
        }
    
        /// <summary>
        /// 用于向 ItemTables EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToItemTables(ItemTable itemTable)
        {
            base.AddObject("ItemTables", itemTable);
        }
    
        /// <summary>
        /// 用于向 MerChantTables EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMerChantTables(MerChantTable merChantTable)
        {
            base.AddObject("MerChantTables", merChantTable);
        }
    
        /// <summary>
        /// 用于向 MessageTables EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMessageTables(MessageTable messageTable)
        {
            base.AddObject("MessageTables", messageTable);
        }
    
        /// <summary>
        /// 用于向 MessageToUserTables EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToMessageToUserTables(MessageToUserTable messageToUserTable)
        {
            base.AddObject("MessageToUserTables", messageToUserTable);
        }
    
        /// <summary>
        /// 用于向 PhotoTrendTables EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPhotoTrendTables(PhotoTrendTable photoTrendTable)
        {
            base.AddObject("PhotoTrendTables", photoTrendTable);
        }
    
        /// <summary>
        /// 用于向 PostAffectTables EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPostAffectTables(PostAffectTable postAffectTable)
        {
            base.AddObject("PostAffectTables", postAffectTable);
        }
    
        /// <summary>
        /// 用于向 RewardTables EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToRewardTables(RewardTable rewardTable)
        {
            base.AddObject("RewardTables", rewardTable);
        }
    
        /// <summary>
        /// 用于向 UserTables EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUserTables(UserTable userTable)
        {
            base.AddObject("UserTables", userTable);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BecleModel", Name="AchievementTrendTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AchievementTrendTable : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 AchievementTrendTable 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="userId">UserId 属性的初始值。</param>
        /// <param name="achievement">Achievement 属性的初始值。</param>
        /// <param name="time">Time 属性的初始值。</param>
        public static AchievementTrendTable CreateAchievementTrendTable(global::System.Int32 id, global::System.Int32 userId, global::System.String achievement, global::System.String time)
        {
            AchievementTrendTable achievementTrendTable = new AchievementTrendTable();
            achievementTrendTable.Id = id;
            achievementTrendTable.UserId = userId;
            achievementTrendTable.Achievement = achievement;
            achievementTrendTable.Time = time;
            return achievementTrendTable;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Achievement
        {
            get
            {
                return _Achievement;
            }
            set
            {
                OnAchievementChanging(value);
                ReportPropertyChanging("Achievement");
                _Achievement = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Achievement");
                OnAchievementChanged();
            }
        }
        private global::System.String _Achievement;
        partial void OnAchievementChanging(global::System.String value);
        partial void OnAchievementChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.String _Time;
        partial void OnTimeChanging(global::System.String value);
        partial void OnTimeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BecleModel", Name="AcquirerTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AcquirerTable : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 AcquirerTable 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="passWord">PassWord 属性的初始值。</param>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="binName">BinName 属性的初始值。</param>
        /// <param name="latitude">Latitude 属性的初始值。</param>
        /// <param name="longitude">Longitude 属性的初始值。</param>
        /// <param name="city">City 属性的初始值。</param>
        /// <param name="address">Address 属性的初始值。</param>
        /// <param name="avatar">Avatar 属性的初始值。</param>
        /// <param name="phone">Phone 属性的初始值。</param>
        public static AcquirerTable CreateAcquirerTable(global::System.Int32 id, global::System.String passWord, global::System.String userName, global::System.String binName, global::System.Decimal latitude, global::System.Decimal longitude, global::System.String city, global::System.String address, global::System.Byte[] avatar, global::System.String phone)
        {
            AcquirerTable acquirerTable = new AcquirerTable();
            acquirerTable.Id = id;
            acquirerTable.PassWord = passWord;
            acquirerTable.UserName = userName;
            acquirerTable.BinName = binName;
            acquirerTable.Latitude = latitude;
            acquirerTable.Longitude = longitude;
            acquirerTable.City = city;
            acquirerTable.Address = address;
            acquirerTable.Avatar = avatar;
            acquirerTable.Phone = phone;
            return acquirerTable;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PassWord
        {
            get
            {
                return _PassWord;
            }
            set
            {
                OnPassWordChanging(value);
                ReportPropertyChanging("PassWord");
                _PassWord = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PassWord");
                OnPassWordChanged();
            }
        }
        private global::System.String _PassWord;
        partial void OnPassWordChanging(global::System.String value);
        partial void OnPassWordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BinName
        {
            get
            {
                return _BinName;
            }
            set
            {
                OnBinNameChanging(value);
                ReportPropertyChanging("BinName");
                _BinName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("BinName");
                OnBinNameChanged();
            }
        }
        private global::System.String _BinName;
        partial void OnBinNameChanging(global::System.String value);
        partial void OnBinNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Decimal _Latitude;
        partial void OnLatitudeChanging(global::System.Decimal value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Decimal _Longitude;
        partial void OnLongitudeChanging(global::System.Decimal value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Avatar
        {
            get
            {
                return StructuralObject.GetValidValue(_Avatar);
            }
            set
            {
                OnAvatarChanging(value);
                ReportPropertyChanging("Avatar");
                _Avatar = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Avatar");
                OnAvatarChanged();
            }
        }
        private global::System.Byte[] _Avatar;
        partial void OnAvatarChanging(global::System.Byte[] value);
        partial void OnAvatarChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BecleModel", Name="CategoryTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CategoryTable : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 CategoryTable 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        public static CategoryTable CreateCategoryTable(global::System.Int32 id, global::System.String name)
        {
            CategoryTable categoryTable = new CategoryTable();
            categoryTable.Id = id;
            categoryTable.Name = name;
            return categoryTable;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Describe
        {
            get
            {
                return _Describe;
            }
            set
            {
                OnDescribeChanging(value);
                ReportPropertyChanging("Describe");
                _Describe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Describe");
                OnDescribeChanged();
            }
        }
        private global::System.String _Describe;
        partial void OnDescribeChanging(global::System.String value);
        partial void OnDescribeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BecleModel", Name="CityTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CityTable : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 CityTable 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="point">Point 属性的初始值。</param>
        /// <param name="lastRank">LastRank 属性的初始值。</param>
        public static CityTable CreateCityTable(global::System.Int32 id, global::System.String name, global::System.Int32 point, global::System.Int32 lastRank)
        {
            CityTable cityTable = new CityTable();
            cityTable.Id = id;
            cityTable.Name = name;
            cityTable.Point = point;
            cityTable.LastRank = lastRank;
            return cityTable;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Point
        {
            get
            {
                return _Point;
            }
            set
            {
                OnPointChanging(value);
                ReportPropertyChanging("Point");
                _Point = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Point");
                OnPointChanged();
            }
        }
        private global::System.Int32 _Point;
        partial void OnPointChanging(global::System.Int32 value);
        partial void OnPointChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LastRank
        {
            get
            {
                return _LastRank;
            }
            set
            {
                OnLastRankChanging(value);
                ReportPropertyChanging("LastRank");
                _LastRank = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastRank");
                OnLastRankChanged();
            }
        }
        private global::System.Int32 _LastRank;
        partial void OnLastRankChanging(global::System.Int32 value);
        partial void OnLastRankChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BecleModel", Name="FriendTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FriendTable : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 FriendTable 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="userId">UserId 属性的初始值。</param>
        /// <param name="friendId">FriendId 属性的初始值。</param>
        public static FriendTable CreateFriendTable(global::System.Int32 id, global::System.Int32 userId, global::System.Int32 friendId)
        {
            FriendTable friendTable = new FriendTable();
            friendTable.Id = id;
            friendTable.UserId = userId;
            friendTable.FriendId = friendId;
            return friendTable;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FriendId
        {
            get
            {
                return _FriendId;
            }
            set
            {
                OnFriendIdChanging(value);
                ReportPropertyChanging("FriendId");
                _FriendId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FriendId");
                OnFriendIdChanged();
            }
        }
        private global::System.Int32 _FriendId;
        partial void OnFriendIdChanging(global::System.Int32 value);
        partial void OnFriendIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BecleModel", Name="ItemTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ItemTable : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 ItemTable 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="name">Name 属性的初始值。</param>
        /// <param name="userId">UserId 属性的初始值。</param>
        /// <param name="categoryId">CategoryId 属性的初始值。</param>
        /// <param name="amount">Amount 属性的初始值。</param>
        /// <param name="image">Image 属性的初始值。</param>
        /// <param name="time">Time 属性的初始值。</param>
        /// <param name="describe">Describe 属性的初始值。</param>
        public static ItemTable CreateItemTable(global::System.Int32 id, global::System.String name, global::System.Int32 userId, global::System.Int32 categoryId, global::System.Int32 amount, global::System.Byte[] image, global::System.String time, global::System.String describe)
        {
            ItemTable itemTable = new ItemTable();
            itemTable.Id = id;
            itemTable.Name = name;
            itemTable.UserId = userId;
            itemTable.CategoryId = categoryId;
            itemTable.Amount = amount;
            itemTable.Image = image;
            itemTable.Time = time;
            itemTable.Describe = describe;
            return itemTable;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CategoryId
        {
            get
            {
                return _CategoryId;
            }
            set
            {
                OnCategoryIdChanging(value);
                ReportPropertyChanging("CategoryId");
                _CategoryId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CategoryId");
                OnCategoryIdChanged();
            }
        }
        private global::System.Int32 _CategoryId;
        partial void OnCategoryIdChanging(global::System.Int32 value);
        partial void OnCategoryIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Int32 _Amount;
        partial void OnAmountChanging(global::System.Int32 value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.String _Time;
        partial void OnTimeChanging(global::System.String value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Describe
        {
            get
            {
                return _Describe;
            }
            set
            {
                OnDescribeChanging(value);
                ReportPropertyChanging("Describe");
                _Describe = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Describe");
                OnDescribeChanged();
            }
        }
        private global::System.String _Describe;
        partial void OnDescribeChanging(global::System.String value);
        partial void OnDescribeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BecleModel", Name="MerChantTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MerChantTable : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MerChantTable 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="passWord">PassWord 属性的初始值。</param>
        /// <param name="phone">Phone 属性的初始值。</param>
        /// <param name="longitude">Longitude 属性的初始值。</param>
        /// <param name="latitude">Latitude 属性的初始值。</param>
        /// <param name="address">Address 属性的初始值。</param>
        /// <param name="storeName">StoreName 属性的初始值。</param>
        /// <param name="avatar">Avatar 属性的初始值。</param>
        public static MerChantTable CreateMerChantTable(global::System.Int32 id, global::System.String userName, global::System.String passWord, global::System.String phone, global::System.Decimal longitude, global::System.Decimal latitude, global::System.String address, global::System.String storeName, global::System.Byte[] avatar)
        {
            MerChantTable merChantTable = new MerChantTable();
            merChantTable.Id = id;
            merChantTable.UserName = userName;
            merChantTable.PassWord = passWord;
            merChantTable.Phone = phone;
            merChantTable.Longitude = longitude;
            merChantTable.Latitude = latitude;
            merChantTable.Address = address;
            merChantTable.StoreName = storeName;
            merChantTable.Avatar = avatar;
            return merChantTable;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PassWord
        {
            get
            {
                return _PassWord;
            }
            set
            {
                OnPassWordChanging(value);
                ReportPropertyChanging("PassWord");
                _PassWord = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PassWord");
                OnPassWordChanged();
            }
        }
        private global::System.String _PassWord;
        partial void OnPassWordChanging(global::System.String value);
        partial void OnPassWordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Decimal _Longitude;
        partial void OnLongitudeChanging(global::System.Decimal value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Decimal _Latitude;
        partial void OnLatitudeChanging(global::System.Decimal value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StoreName
        {
            get
            {
                return _StoreName;
            }
            set
            {
                OnStoreNameChanging(value);
                ReportPropertyChanging("StoreName");
                _StoreName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StoreName");
                OnStoreNameChanged();
            }
        }
        private global::System.String _StoreName;
        partial void OnStoreNameChanging(global::System.String value);
        partial void OnStoreNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Avatar
        {
            get
            {
                return StructuralObject.GetValidValue(_Avatar);
            }
            set
            {
                OnAvatarChanging(value);
                ReportPropertyChanging("Avatar");
                _Avatar = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Avatar");
                OnAvatarChanged();
            }
        }
        private global::System.Byte[] _Avatar;
        partial void OnAvatarChanging(global::System.Byte[] value);
        partial void OnAvatarChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BecleModel", Name="MessageTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MessageTable : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MessageTable 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="fromId">FromId 属性的初始值。</param>
        /// <param name="toId">ToId 属性的初始值。</param>
        /// <param name="isSee">IsSee 属性的初始值。</param>
        /// <param name="message">Message 属性的初始值。</param>
        /// <param name="time">Time 属性的初始值。</param>
        public static MessageTable CreateMessageTable(global::System.Int32 id, global::System.Int32 fromId, global::System.Int32 toId, global::System.Boolean isSee, global::System.String message, global::System.String time)
        {
            MessageTable messageTable = new MessageTable();
            messageTable.Id = id;
            messageTable.FromId = fromId;
            messageTable.ToId = toId;
            messageTable.IsSee = isSee;
            messageTable.Message = message;
            messageTable.Time = time;
            return messageTable;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FromId
        {
            get
            {
                return _FromId;
            }
            set
            {
                OnFromIdChanging(value);
                ReportPropertyChanging("FromId");
                _FromId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FromId");
                OnFromIdChanged();
            }
        }
        private global::System.Int32 _FromId;
        partial void OnFromIdChanging(global::System.Int32 value);
        partial void OnFromIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ToId
        {
            get
            {
                return _ToId;
            }
            set
            {
                OnToIdChanging(value);
                ReportPropertyChanging("ToId");
                _ToId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ToId");
                OnToIdChanged();
            }
        }
        private global::System.Int32 _ToId;
        partial void OnToIdChanging(global::System.Int32 value);
        partial void OnToIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSee
        {
            get
            {
                return _IsSee;
            }
            set
            {
                OnIsSeeChanging(value);
                ReportPropertyChanging("IsSee");
                _IsSee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSee");
                OnIsSeeChanged();
            }
        }
        private global::System.Boolean _IsSee;
        partial void OnIsSeeChanging(global::System.Boolean value);
        partial void OnIsSeeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.String _Time;
        partial void OnTimeChanging(global::System.String value);
        partial void OnTimeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BecleModel", Name="MessageToUserTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MessageToUserTable : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 MessageToUserTable 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="fromId">FromId 属性的初始值。</param>
        /// <param name="toId">ToId 属性的初始值。</param>
        /// <param name="messageContent">MessageContent 属性的初始值。</param>
        /// <param name="time">Time 属性的初始值。</param>
        /// <param name="isSee">IsSee 属性的初始值。</param>
        /// <param name="type">Type 属性的初始值。</param>
        public static MessageToUserTable CreateMessageToUserTable(global::System.Int32 id, global::System.Int32 fromId, global::System.Int32 toId, global::System.String messageContent, global::System.String time, global::System.Boolean isSee, global::System.Int32 type)
        {
            MessageToUserTable messageToUserTable = new MessageToUserTable();
            messageToUserTable.Id = id;
            messageToUserTable.FromId = fromId;
            messageToUserTable.ToId = toId;
            messageToUserTable.MessageContent = messageContent;
            messageToUserTable.Time = time;
            messageToUserTable.IsSee = isSee;
            messageToUserTable.Type = type;
            return messageToUserTable;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FromId
        {
            get
            {
                return _FromId;
            }
            set
            {
                OnFromIdChanging(value);
                ReportPropertyChanging("FromId");
                _FromId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FromId");
                OnFromIdChanged();
            }
        }
        private global::System.Int32 _FromId;
        partial void OnFromIdChanging(global::System.Int32 value);
        partial void OnFromIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ToId
        {
            get
            {
                return _ToId;
            }
            set
            {
                OnToIdChanging(value);
                ReportPropertyChanging("ToId");
                _ToId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ToId");
                OnToIdChanged();
            }
        }
        private global::System.Int32 _ToId;
        partial void OnToIdChanging(global::System.Int32 value);
        partial void OnToIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MessageContent
        {
            get
            {
                return _MessageContent;
            }
            set
            {
                OnMessageContentChanging(value);
                ReportPropertyChanging("MessageContent");
                _MessageContent = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MessageContent");
                OnMessageContentChanged();
            }
        }
        private global::System.String _MessageContent;
        partial void OnMessageContentChanging(global::System.String value);
        partial void OnMessageContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.String _Time;
        partial void OnTimeChanging(global::System.String value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSee
        {
            get
            {
                return _IsSee;
            }
            set
            {
                OnIsSeeChanging(value);
                ReportPropertyChanging("IsSee");
                _IsSee = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSee");
                OnIsSeeChanged();
            }
        }
        private global::System.Boolean _IsSee;
        partial void OnIsSeeChanging(global::System.Boolean value);
        partial void OnIsSeeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Int32 _Type;
        partial void OnTypeChanging(global::System.Int32 value);
        partial void OnTypeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BecleModel", Name="PhotoTrendTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PhotoTrendTable : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 PhotoTrendTable 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="userId">UserId 属性的初始值。</param>
        /// <param name="describe">Describe 属性的初始值。</param>
        /// <param name="time">Time 属性的初始值。</param>
        /// <param name="itemId">ItemId 属性的初始值。</param>
        public static PhotoTrendTable CreatePhotoTrendTable(global::System.Int32 id, global::System.Int32 userId, global::System.String describe, global::System.String time, global::System.Int32 itemId)
        {
            PhotoTrendTable photoTrendTable = new PhotoTrendTable();
            photoTrendTable.Id = id;
            photoTrendTable.UserId = userId;
            photoTrendTable.Describe = describe;
            photoTrendTable.Time = time;
            photoTrendTable.ItemId = itemId;
            return photoTrendTable;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Describe
        {
            get
            {
                return _Describe;
            }
            set
            {
                OnDescribeChanging(value);
                ReportPropertyChanging("Describe");
                _Describe = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Describe");
                OnDescribeChanged();
            }
        }
        private global::System.String _Describe;
        partial void OnDescribeChanging(global::System.String value);
        partial void OnDescribeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.String _Time;
        partial void OnTimeChanging(global::System.String value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItemId
        {
            get
            {
                return _ItemId;
            }
            set
            {
                OnItemIdChanging(value);
                ReportPropertyChanging("ItemId");
                _ItemId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItemId");
                OnItemIdChanged();
            }
        }
        private global::System.Int32 _ItemId;
        partial void OnItemIdChanging(global::System.Int32 value);
        partial void OnItemIdChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BecleModel", Name="PostAffectTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PostAffectTable : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 PostAffectTable 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="userId">UserId 属性的初始值。</param>
        /// <param name="describe">Describe 属性的初始值。</param>
        /// <param name="time">Time 属性的初始值。</param>
        /// <param name="postAffect">PostAffect 属性的初始值。</param>
        public static PostAffectTable CreatePostAffectTable(global::System.Int32 id, global::System.Int32 userId, global::System.String describe, global::System.String time, global::System.String postAffect)
        {
            PostAffectTable postAffectTable = new PostAffectTable();
            postAffectTable.Id = id;
            postAffectTable.UserId = userId;
            postAffectTable.Describe = describe;
            postAffectTable.Time = time;
            postAffectTable.PostAffect = postAffect;
            return postAffectTable;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Describe
        {
            get
            {
                return _Describe;
            }
            set
            {
                OnDescribeChanging(value);
                ReportPropertyChanging("Describe");
                _Describe = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Describe");
                OnDescribeChanged();
            }
        }
        private global::System.String _Describe;
        partial void OnDescribeChanging(global::System.String value);
        partial void OnDescribeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.String _Time;
        partial void OnTimeChanging(global::System.String value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PostAffect
        {
            get
            {
                return _PostAffect;
            }
            set
            {
                OnPostAffectChanging(value);
                ReportPropertyChanging("PostAffect");
                _PostAffect = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PostAffect");
                OnPostAffectChanged();
            }
        }
        private global::System.String _PostAffect;
        partial void OnPostAffectChanging(global::System.String value);
        partial void OnPostAffectChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BecleModel", Name="RewardTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RewardTable : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 RewardTable 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="storeName">StoreName 属性的初始值。</param>
        /// <param name="latitude">Latitude 属性的初始值。</param>
        /// <param name="longitude">Longitude 属性的初始值。</param>
        /// <param name="address">Address 属性的初始值。</param>
        /// <param name="phone">Phone 属性的初始值。</param>
        /// <param name="city">City 属性的初始值。</param>
        /// <param name="describe">Describe 属性的初始值。</param>
        public static RewardTable CreateRewardTable(global::System.Int32 id, global::System.String storeName, global::System.Decimal latitude, global::System.Decimal longitude, global::System.String address, global::System.String phone, global::System.String city, global::System.String describe)
        {
            RewardTable rewardTable = new RewardTable();
            rewardTable.Id = id;
            rewardTable.StoreName = storeName;
            rewardTable.Latitude = latitude;
            rewardTable.Longitude = longitude;
            rewardTable.Address = address;
            rewardTable.Phone = phone;
            rewardTable.City = city;
            rewardTable.Describe = describe;
            return rewardTable;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StoreName
        {
            get
            {
                return _StoreName;
            }
            set
            {
                OnStoreNameChanging(value);
                ReportPropertyChanging("StoreName");
                _StoreName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StoreName");
                OnStoreNameChanged();
            }
        }
        private global::System.String _StoreName;
        partial void OnStoreNameChanging(global::System.String value);
        partial void OnStoreNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Decimal _Latitude;
        partial void OnLatitudeChanging(global::System.Decimal value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Decimal _Longitude;
        partial void OnLongitudeChanging(global::System.Decimal value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Describe
        {
            get
            {
                return _Describe;
            }
            set
            {
                OnDescribeChanging(value);
                ReportPropertyChanging("Describe");
                _Describe = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Describe");
                OnDescribeChanged();
            }
        }
        private global::System.String _Describe;
        partial void OnDescribeChanging(global::System.String value);
        partial void OnDescribeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BecleModel", Name="UserTable")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserTable : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 UserTable 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="latitude">Latitude 属性的初始值。</param>
        /// <param name="longitude">Longitude 属性的初始值。</param>
        /// <param name="point">Point 属性的初始值。</param>
        /// <param name="cityLastRank">CityLastRank 属性的初始值。</param>
        /// <param name="nowCityRank">NowCityRank 属性的初始值。</param>
        /// <param name="nowRank">NowRank 属性的初始值。</param>
        /// <param name="lastRank">LastRank 属性的初始值。</param>
        /// <param name="avatar">Avatar 属性的初始值。</param>
        /// <param name="address">Address 属性的初始值。</param>
        /// <param name="city">City 属性的初始值。</param>
        /// <param name="password">Password 属性的初始值。</param>
        public static UserTable CreateUserTable(global::System.Int32 id, global::System.String userName, global::System.Decimal latitude, global::System.Decimal longitude, global::System.Int32 point, global::System.Int32 cityLastRank, global::System.Int32 nowCityRank, global::System.Int32 nowRank, global::System.Int32 lastRank, global::System.Byte[] avatar, global::System.String address, global::System.String city, global::System.String password)
        {
            UserTable userTable = new UserTable();
            userTable.Id = id;
            userTable.UserName = userName;
            userTable.Latitude = latitude;
            userTable.Longitude = longitude;
            userTable.Point = point;
            userTable.CityLastRank = cityLastRank;
            userTable.NowCityRank = nowCityRank;
            userTable.NowRank = nowRank;
            userTable.LastRank = lastRank;
            userTable.Avatar = avatar;
            userTable.Address = address;
            userTable.City = city;
            userTable.Password = password;
            return userTable;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.Decimal _Latitude;
        partial void OnLatitudeChanging(global::System.Decimal value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.Decimal _Longitude;
        partial void OnLongitudeChanging(global::System.Decimal value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Point
        {
            get
            {
                return _Point;
            }
            set
            {
                OnPointChanging(value);
                ReportPropertyChanging("Point");
                _Point = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Point");
                OnPointChanged();
            }
        }
        private global::System.Int32 _Point;
        partial void OnPointChanging(global::System.Int32 value);
        partial void OnPointChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CityLastRank
        {
            get
            {
                return _CityLastRank;
            }
            set
            {
                OnCityLastRankChanging(value);
                ReportPropertyChanging("CityLastRank");
                _CityLastRank = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CityLastRank");
                OnCityLastRankChanged();
            }
        }
        private global::System.Int32 _CityLastRank;
        partial void OnCityLastRankChanging(global::System.Int32 value);
        partial void OnCityLastRankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NowCityRank
        {
            get
            {
                return _NowCityRank;
            }
            set
            {
                OnNowCityRankChanging(value);
                ReportPropertyChanging("NowCityRank");
                _NowCityRank = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NowCityRank");
                OnNowCityRankChanged();
            }
        }
        private global::System.Int32 _NowCityRank;
        partial void OnNowCityRankChanging(global::System.Int32 value);
        partial void OnNowCityRankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NowRank
        {
            get
            {
                return _NowRank;
            }
            set
            {
                OnNowRankChanging(value);
                ReportPropertyChanging("NowRank");
                _NowRank = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NowRank");
                OnNowRankChanged();
            }
        }
        private global::System.Int32 _NowRank;
        partial void OnNowRankChanging(global::System.Int32 value);
        partial void OnNowRankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LastRank
        {
            get
            {
                return _LastRank;
            }
            set
            {
                OnLastRankChanging(value);
                ReportPropertyChanging("LastRank");
                _LastRank = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastRank");
                OnLastRankChanged();
            }
        }
        private global::System.Int32 _LastRank;
        partial void OnLastRankChanging(global::System.Int32 value);
        partial void OnLastRankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Avatar
        {
            get
            {
                return StructuralObject.GetValidValue(_Avatar);
            }
            set
            {
                OnAvatarChanging(value);
                ReportPropertyChanging("Avatar");
                _Avatar = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Avatar");
                OnAvatarChanged();
            }
        }
        private global::System.Byte[] _Avatar;
        partial void OnAvatarChanging(global::System.Byte[] value);
        partial void OnAvatarChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserRank
        {
            get
            {
                return _UserRank;
            }
            set
            {
                OnUserRankChanging(value);
                ReportPropertyChanging("UserRank");
                _UserRank = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserRank");
                OnUserRankChanged();
            }
        }
        private Nullable<global::System.Int32> _UserRank;
        partial void OnUserRankChanging(Nullable<global::System.Int32> value);
        partial void OnUserRankChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CityRank
        {
            get
            {
                return _CityRank;
            }
            set
            {
                OnCityRankChanging(value);
                ReportPropertyChanging("CityRank");
                _CityRank = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CityRank");
                OnCityRankChanged();
            }
        }
        private Nullable<global::System.Int32> _CityRank;
        partial void OnCityRankChanging(Nullable<global::System.Int32> value);
        partial void OnCityRankChanged();

        #endregion
    
    }

    #endregion
    
}
