//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace Panda.Phone.Acquirer.AcquirerServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adrress", Namespace="http://schemas.datacontract.org/2004/07/Panda.Phone.DataModel")]
    public partial class Adrress : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Panda.Phone.DataModel")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Items", Namespace="http://schemas.datacontract.org/2004/07/Panda.Phone.DataModel")]
    public partial class Items : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CategoryIdField;
        
        private int IdField;
        
        private string NameField;
        
        private int NumField;
        
        private int UserIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Num {
            get {
                return this.NumField;
            }
            set {
                if ((this.NumField.Equals(value) != true)) {
                    this.NumField = value;
                    this.RaisePropertyChanged("Num");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AcquirerServiceReference.IAcquirerService")]
    public interface IAcquirerService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAcquirerService/GetChoicedPoint", ReplyAction="http://tempuri.org/IAcquirerService/GetChoicedPointResponse")]
        System.IAsyncResult BeginGetChoicedPoint(System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Adrress> list, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User> EndGetChoicedPoint(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAcquirerService/getAllUser", ReplyAction="http://tempuri.org/IAcquirerService/getAllUserResponse")]
        System.IAsyncResult BegingetAllUser(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User> EndgetAllUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAcquirerService/getItemsByUserId", ReplyAction="http://tempuri.org/IAcquirerService/getItemsByUserIdResponse")]
        System.IAsyncResult BegingetItemsByUserId(int Id, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items> EndgetItemsByUserId(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IAcquirerService/getItemsByCategoryId", ReplyAction="http://tempuri.org/IAcquirerService/getItemsByCategoryIdResponse")]
        System.IAsyncResult BegingetItemsByCategoryId(int Id, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items> EndgetItemsByCategoryId(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAcquirerServiceChannel : Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetChoicedPointCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetChoicedPointCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getAllUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getAllUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getItemsByUserIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getItemsByUserIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getItemsByCategoryIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getItemsByCategoryIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AcquirerServiceClient : System.ServiceModel.ClientBase<Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService>, Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService {
        
        private BeginOperationDelegate onBeginGetChoicedPointDelegate;
        
        private EndOperationDelegate onEndGetChoicedPointDelegate;
        
        private System.Threading.SendOrPostCallback onGetChoicedPointCompletedDelegate;
        
        private BeginOperationDelegate onBegingetAllUserDelegate;
        
        private EndOperationDelegate onEndgetAllUserDelegate;
        
        private System.Threading.SendOrPostCallback ongetAllUserCompletedDelegate;
        
        private BeginOperationDelegate onBegingetItemsByUserIdDelegate;
        
        private EndOperationDelegate onEndgetItemsByUserIdDelegate;
        
        private System.Threading.SendOrPostCallback ongetItemsByUserIdCompletedDelegate;
        
        private BeginOperationDelegate onBegingetItemsByCategoryIdDelegate;
        
        private EndOperationDelegate onEndgetItemsByCategoryIdDelegate;
        
        private System.Threading.SendOrPostCallback ongetItemsByCategoryIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public AcquirerServiceClient() {
        }
        
        public AcquirerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AcquirerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcquirerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AcquirerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetChoicedPointCompletedEventArgs> GetChoicedPointCompleted;
        
        public event System.EventHandler<getAllUserCompletedEventArgs> getAllUserCompleted;
        
        public event System.EventHandler<getItemsByUserIdCompletedEventArgs> getItemsByUserIdCompleted;
        
        public event System.EventHandler<getItemsByCategoryIdCompletedEventArgs> getItemsByCategoryIdCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService.BeginGetChoicedPoint(System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Adrress> list, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetChoicedPoint(list, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User> Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService.EndGetChoicedPoint(System.IAsyncResult result) {
            return base.Channel.EndGetChoicedPoint(result);
        }
        
        private System.IAsyncResult OnBeginGetChoicedPoint(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Adrress> list = ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Adrress>)(inValues[0]));
            return ((Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService)(this)).BeginGetChoicedPoint(list, callback, asyncState);
        }
        
        private object[] OnEndGetChoicedPoint(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User> retVal = ((Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService)(this)).EndGetChoicedPoint(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetChoicedPointCompleted(object state) {
            if ((this.GetChoicedPointCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetChoicedPointCompleted(this, new GetChoicedPointCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetChoicedPointAsync(System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Adrress> list) {
            this.GetChoicedPointAsync(list, null);
        }
        
        public void GetChoicedPointAsync(System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Adrress> list, object userState) {
            if ((this.onBeginGetChoicedPointDelegate == null)) {
                this.onBeginGetChoicedPointDelegate = new BeginOperationDelegate(this.OnBeginGetChoicedPoint);
            }
            if ((this.onEndGetChoicedPointDelegate == null)) {
                this.onEndGetChoicedPointDelegate = new EndOperationDelegate(this.OnEndGetChoicedPoint);
            }
            if ((this.onGetChoicedPointCompletedDelegate == null)) {
                this.onGetChoicedPointCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetChoicedPointCompleted);
            }
            base.InvokeAsync(this.onBeginGetChoicedPointDelegate, new object[] {
                        list}, this.onEndGetChoicedPointDelegate, this.onGetChoicedPointCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService.BegingetAllUser(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetAllUser(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User> Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService.EndgetAllUser(System.IAsyncResult result) {
            return base.Channel.EndgetAllUser(result);
        }
        
        private System.IAsyncResult OnBegingetAllUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService)(this)).BegingetAllUser(callback, asyncState);
        }
        
        private object[] OnEndgetAllUser(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User> retVal = ((Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService)(this)).EndgetAllUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetAllUserCompleted(object state) {
            if ((this.getAllUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getAllUserCompleted(this, new getAllUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getAllUserAsync() {
            this.getAllUserAsync(null);
        }
        
        public void getAllUserAsync(object userState) {
            if ((this.onBegingetAllUserDelegate == null)) {
                this.onBegingetAllUserDelegate = new BeginOperationDelegate(this.OnBegingetAllUser);
            }
            if ((this.onEndgetAllUserDelegate == null)) {
                this.onEndgetAllUserDelegate = new EndOperationDelegate(this.OnEndgetAllUser);
            }
            if ((this.ongetAllUserCompletedDelegate == null)) {
                this.ongetAllUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetAllUserCompleted);
            }
            base.InvokeAsync(this.onBegingetAllUserDelegate, null, this.onEndgetAllUserDelegate, this.ongetAllUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService.BegingetItemsByUserId(int Id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetItemsByUserId(Id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items> Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService.EndgetItemsByUserId(System.IAsyncResult result) {
            return base.Channel.EndgetItemsByUserId(result);
        }
        
        private System.IAsyncResult OnBegingetItemsByUserId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int Id = ((int)(inValues[0]));
            return ((Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService)(this)).BegingetItemsByUserId(Id, callback, asyncState);
        }
        
        private object[] OnEndgetItemsByUserId(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items> retVal = ((Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService)(this)).EndgetItemsByUserId(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetItemsByUserIdCompleted(object state) {
            if ((this.getItemsByUserIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getItemsByUserIdCompleted(this, new getItemsByUserIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getItemsByUserIdAsync(int Id) {
            this.getItemsByUserIdAsync(Id, null);
        }
        
        public void getItemsByUserIdAsync(int Id, object userState) {
            if ((this.onBegingetItemsByUserIdDelegate == null)) {
                this.onBegingetItemsByUserIdDelegate = new BeginOperationDelegate(this.OnBegingetItemsByUserId);
            }
            if ((this.onEndgetItemsByUserIdDelegate == null)) {
                this.onEndgetItemsByUserIdDelegate = new EndOperationDelegate(this.OnEndgetItemsByUserId);
            }
            if ((this.ongetItemsByUserIdCompletedDelegate == null)) {
                this.ongetItemsByUserIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetItemsByUserIdCompleted);
            }
            base.InvokeAsync(this.onBegingetItemsByUserIdDelegate, new object[] {
                        Id}, this.onEndgetItemsByUserIdDelegate, this.ongetItemsByUserIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService.BegingetItemsByCategoryId(int Id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetItemsByCategoryId(Id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items> Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService.EndgetItemsByCategoryId(System.IAsyncResult result) {
            return base.Channel.EndgetItemsByCategoryId(result);
        }
        
        private System.IAsyncResult OnBegingetItemsByCategoryId(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int Id = ((int)(inValues[0]));
            return ((Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService)(this)).BegingetItemsByCategoryId(Id, callback, asyncState);
        }
        
        private object[] OnEndgetItemsByCategoryId(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items> retVal = ((Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService)(this)).EndgetItemsByCategoryId(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetItemsByCategoryIdCompleted(object state) {
            if ((this.getItemsByCategoryIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getItemsByCategoryIdCompleted(this, new getItemsByCategoryIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getItemsByCategoryIdAsync(int Id) {
            this.getItemsByCategoryIdAsync(Id, null);
        }
        
        public void getItemsByCategoryIdAsync(int Id, object userState) {
            if ((this.onBegingetItemsByCategoryIdDelegate == null)) {
                this.onBegingetItemsByCategoryIdDelegate = new BeginOperationDelegate(this.OnBegingetItemsByCategoryId);
            }
            if ((this.onEndgetItemsByCategoryIdDelegate == null)) {
                this.onEndgetItemsByCategoryIdDelegate = new EndOperationDelegate(this.OnEndgetItemsByCategoryId);
            }
            if ((this.ongetItemsByCategoryIdCompletedDelegate == null)) {
                this.ongetItemsByCategoryIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetItemsByCategoryIdCompleted);
            }
            base.InvokeAsync(this.onBegingetItemsByCategoryIdDelegate, new object[] {
                        Id}, this.onEndgetItemsByCategoryIdDelegate, this.ongetItemsByCategoryIdCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService CreateChannel() {
            return new AcquirerServiceClientChannel(this);
        }
        
        private class AcquirerServiceClientChannel : ChannelBase<Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService>, Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService {
            
            public AcquirerServiceClientChannel(System.ServiceModel.ClientBase<Panda.Phone.Acquirer.AcquirerServiceReference.IAcquirerService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetChoicedPoint(System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Adrress> list, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = list;
                System.IAsyncResult _result = base.BeginInvoke("GetChoicedPoint", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User> EndGetChoicedPoint(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User> _result = ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User>)(base.EndInvoke("GetChoicedPoint", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetAllUser(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getAllUser", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User> EndgetAllUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User> _result = ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.User>)(base.EndInvoke("getAllUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetItemsByUserId(int Id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Id;
                System.IAsyncResult _result = base.BeginInvoke("getItemsByUserId", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items> EndgetItemsByUserId(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items> _result = ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items>)(base.EndInvoke("getItemsByUserId", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetItemsByCategoryId(int Id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Id;
                System.IAsyncResult _result = base.BeginInvoke("getItemsByCategoryId", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items> EndgetItemsByCategoryId(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items> _result = ((System.Collections.ObjectModel.ObservableCollection<Panda.Phone.Acquirer.AcquirerServiceReference.Items>)(base.EndInvoke("getItemsByCategoryId", _args, result)));
                return _result;
            }
        }
    }
}
